# Generated by Django 4.1.7 on 2023-08-08 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_rename_tasks_task"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="donde",
            new_name="done",
        ),
    ]
